<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <NuGetAudit>false</NuGetAudit>
    <ApplicationIcon>Icons\MainWnd.ico</ApplicationIcon>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Resources\**\*" />
    <None Remove="Scenes\**\*" />
    <None Remove="Ads\**\*" />
    <None Remove="Icons\**\*" />
    <Resource Include="Resources\**\*" />
    <Resource Include="Scenes\**\*" />
    <Resource Include="Ads\**\*" />
    <Resource Include="Icons\**\*" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="XamlAnimatedGif" Version="2.3.0" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
  </ItemGroup>
</Project>
